import React from 'react'
import '../style/style.css'
import { FaArrowDown } from "react-icons/fa"

export default function aboutSection() {
    return (
        <div >

            <div className='about-div1'>

                <div>
                    <img src={require('../assets/images/Group 1.png')} alt='who we are' height={400} width={400}/>
                    <p id="whoweare">who we are</p>
                </div>

                <div>
                    {/* <img src={require('../assets/images/Group 1.png')} alt='who we are' height={400} width={400}/> */}
                    <h6 id='descri_1' > If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.</h6>
                </div>
                
            </div>


            <div className='about-div2'>


                <div>
                    {/* <img src={require('../assets/images/Group 1.png')} alt='who we are' height={400} width={400}/> */}
                    <h6 id='descri_2' > If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.</h6>
                </div>

                <div>
                    <img src={require('../assets/images/Group 2.png')} alt='who we are' height={400} width={400}/>
                    <p id="whatwedo">what we do</p>
                </div>

                
                
            </div>


            <div className='pillarSection'>
                <img src={require('../assets/images/Group 148.png')} alt='header section' width='100%' height='100%'/>
                <p id='about-pillar'>pillars</p>
                <FaArrowDown id='pillarIcon'/>
            </div>  

            
        </div>
    )
}
